---
- name: git module demo
  hosts: all
  become: true

  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
    - name: checkout git repo
      ansible.builtin.git: 
        repo: "https://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@github.com/mnagaraju5628/Testproject-INNO.git"
        dest: "/home/mnagaraju/actions-runner/Testproject-INNO"
