---
- name: Node.js CI - Development Environment
  hosts: development
  gather_facts: true
  become: yes

  tasks:
    - name: Clone repository
      git:
        repo: "https://github.com/your/repository.git"
        dest: "/path/to/your/local/repo"

    - name: Set up Node.js environment
      ansible.builtin.command: "cd /path/to/your/local/repo && npm ci"

    - name: Install gcloud CLI
      community.general.gcp_auth:
        project: "{{ lookup('env', 'GOOGLE_PROJECT') }}"
        credentials_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
        export_default_credentials: true
        install_components:
          - 'gke-gcloud-auth-plugin'

    - name: Build and push Docker image
      ansible.builtin.command: >
        cd /path/to/your/local/repo &&
        gcloud auth configure-docker us-central1-docker.pkg.dev &&
        docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest . &&
        docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest

    - name: Deploy to GKE
      ansible.builtin.command: >
        gcloud container clusters get-credentials innotest-cluster --region us-central1-c &&
        kubectl rollout restart deployment nodeapp-deployment &&
        kubectl apply -f /path/to/your/local/repo/deployment.yaml &&
        kubectl apply -f /path/to/your/local/repo/service.yaml
