- name: Git Checkout, Docker Install, Build Image, Push to Artifact Registry, and Deploy to GKE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main  # replace 'main' with your branch name if different
      become: true

    - name: Build Docker image
      command: docker build -t node .
      args:
        chdir: /home/ubuntu/actions-runner/Testproject-INNO

    - name: Push Docker image to Google Artifact Registry
      command: >
        docker tag node us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      environment:
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Log in to Google Cloud
      command: gcloud auth activate-service-account testgcp-sa@goldengate-1.iam.gserviceaccount.com --key-file=/home/ubuntu/actions-runner/cred.json

    - name: Push Docker image to Google Artifact Registry
      command: >
        docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest

    - name: Set Kubernetes cluster credentials
      command: gcloud container clusters get-credentials innotest-cluster --region us-central1-c
      environment:
        CLOUDSDK_CORE_PROJECT: "goldengate-1"

    - name: Restart deployment
      command: kubectl rollout restart deployment nodeapp-deployment

    - name: Apply deployment configuration
      command: kubectl apply -f deployment.yaml --validate=false

    - name: Apply service configuration
      command: kubectl apply -f service.yaml --validate=false
