- name: Git Checkout, Docker Install, Build Image, Push to Artifact Registry, and Deploy to GKE
  hosts: localhost
  gather_facts: false

  tasks:
    # Existing tasks are kept as they are

- name: Deploy to GKE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get credentials for GKE cluster
      command: gcloud container clusters get-credentials innotest-cluster --region us-central1-c
      register: get_creds_result
      ignore_errors: yes  # Ignoring errors if the command fails

    - name: Ensure Kubernetes credentials are retrieved successfully
      fail:
        msg: "Failed to retrieve Kubernetes credentials: {{ get_creds_result.stderr }}"
      when: get_creds_result.rc != 0  # Fail the task if the command failed

    - name: Restart Deployment
      command: kubectl rollout restart deployment nodeapp-deployment 
      ignore_errors: yes  # Ignore errors since the deployment might already be up to date

    - name: Apply Deployment YAML
      command: kubectl apply -f /home/ubuntu/actions-runner/Testproject-INNO/deployment.yaml 

    - name: Apply Service YAML
      command: kubectl apply -f /home/ubuntu/actions-runner/Testproject-INNO/service.yaml 
