- name: Git Checkout, Docker Install, Build Image, Push to Artifact Registry, and Deploy to GKE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main  # replace 'main' with your branch name if different
      become: true

#   - name: Build Docker Image
#     command: docker build -t node . /home/ubuntu/actions-runner/Testproject-INNO
#     become: true

    - name: Build Docker Image
      command: docker build -t node .
      args:
         chdir: /home/ubuntu/actions-runner/Testproject-INNO
      become: true


    - name: Tag Docker Image
      command: docker tag node us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      become: true

    - name: Push Docker Image to Artifact Registry
      command: docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      become: true

    # Additional tasks for GKE deployment


   
