---
- name: Git Checkout, Docker Install, Build Image, and Push to Artifact Registry
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main
      become: true

    - name: Authenticate with gcloud
      command: "gcloud auth login"
      become: true

    - name: Activate service account if necessary
      command: "gcloud auth activate-service-account inno-test-sa@goldengate-1.iam.gserviceaccount.com"
      become: true
      # Replace ACCOUNT with the service account email

    - name: Build Docker image
      command: "docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest /home/ubuntu/actions-runner/Testproject-INNO"
      become: true

    - name: Push Docker image to artifact registry
      command: "docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest"
      become: true
