---
- name: Run Node.js CI workflow
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io
    - name: Checkout repository
      ansible.builtin.git:
        repo: "https://github.com/mnagaraju5628/Testproject-INNO.git"
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main
      register: checkout

    # Remaining tasks..

    - name: Set gcloud account
      shell: gcloud config set account inno-test-sa@goldengate-1.iam.gserviceaccount.com

    - name: Authenticate Docker with gcloud
      shell: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push the docker image
      shell: |
        docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest .
        docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
        GOOGLE_PROJECT: $GOOGLE_PROJECT
      args:
        chdir: /home/ubuntu/actions-runner/Testproject-INNO

    - name: Deploy to GKE
      shell: |
        gcloud container clusters get-credentials innotest-cluster --region us-central1-c
        kubectl rollout restart deployment nodeapp-deployment 
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      environment:
        GOOGLE_PROJECT: $GOOGLE_PROJECT
      args:
        chdir: /home/ubuntu/actions-runner/Testproject-INNO
