- name: Git Checkout, Docker Install, Build Image, Push to Artifact Registry, and Deploy to GKE
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main  # replace 'main' with your branch name if different
      become: true

    - name: Build Docker image
      become: true
      command: docker build -t node .
      args:
        chdir: /home/ubuntu/actions-runner/Testproject-INNO

    - name: Authenticate Docker with Google Cloud SDK
      become: true
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: /home/ubuntu/actions-runner/Testproject-INNOt-cred.json
      shell: gcloud auth activate-service-account --key-file=/home/ubuntu/actions-runner/Testproject-INNOt-cred.json && gcloud auth configure-docker

    - name: Tag Docker image for Google Artifact Registry
      become: true
      command: docker tag node us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      environment:
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Push Docker image to Google Artifact Registry
      become: true
      command: docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest

    - name: Set project and zone for GKE
      become: true
      shell: gcloud config set project goldengate-1 && gcloud config set compute/zone us-central1-c

    - name: Get credentials for the GKE cluster
      become: true
      shell: gcloud container clusters get-credentials innotest-cluster --region us-central1-c

    - name: Deploy Docker image to GKE (deployment)
      become: true
      command: kubectl apply -f deployment.yaml

    - name: Deploy Docker image to GKE (service)
      become: true
      command: kubectl apply -f service.yaml
