---
- name: Git Checkout, Docker Install, Build Image, and Push to Artifact Registry
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main
      become: true

    - name: Set up gcloud CLI
      become: true
      command: "curl -sSL https://sdk.cloud.google.com | bash"
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Authenticate with service account key
      become: true
      command: "gcloud auth activate-service-account --key-file=/home/ubuntu/actions-runner/Testproject-INNO-cred.json"
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Build Docker image
      command: "docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest /home/ubuntu/actions-runner/Testproject-INNO"
      become: true

    - name: Push Docker image to artifact registry
      command: "docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest"
      become: true
