- name: Trigger GitHub Actions workflow
  hosts: localhost
  gather_facts: false
  vars:
    OWNER: "mnagaraju"
    REPO: "Testproject-INNO"
    WORKFLOW_FILE: "nodejs.yml"
    YOUR_GITHUB_TOKEN: "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"  # Update this with your GitHub Personal Access Token
  tasks:
    - name: Trigger GitHub Actions workflow
      uri:
        url: "https://api.github.com/repos/{{ OWNER }}/{{ REPO }}/actions/workflows/{{ WORKFLOW_FILE }}/dispatches"
        method: POST
        headers:
          Authorization: "token {{ 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 }}"
          Accept: "application/vnd.github.v3+json"
          Content-Type: "application/json"
        body_format: json
        body:
          ref: "main"
          inputs: {}  # If your workflow file has inputs, you can specify them here
      delegate_to: localhost
