---
- name: Build and Deploy
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Checkout code
      git:
        repo: https://github.com/yourusername/yourrepository.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main
      become: true

    - name: Set up Node.js
      ansible.builtin.apt:
        name: nodejs
        update_cache: yes
      become: true

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        update_cache: yes
      become: true

    - name: Install dependencies and build
      ansible.builtin.shell:
        cmd: npm ci && npm run build --if-present && npm install
        chdir: /home/ubuntu/actions-runner/Testproject-INNO
      become: true

    - name: Setup Docker authentication
      ansible.builtin.shell:
        cmd: gcloud auth configure-docker us-central1-docker.pkg.dev
      become: true

    - name: Build Docker Image
      ansible.builtin.command: docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest /home/ubuntu/actions-runner/Testproject-INNO
      become: true

    - name: Push Docker Image
      ansible.builtin.command: docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      become: true
