- name: Git Checkout, Docker Install, Build Image, Push to Artifact Registry, and Deploy to GKE
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Ensure Docker dependencies are installed
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - docker.io

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /home/ubuntu/actions-runner/Testproject-INNO
        version: main  # replace 'main' with your branch name if different
      become: true

    - name: Build Docker image
      command: docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest .
      args:
        chdir: /home/ubuntu/actions-runner/Testproject-INNO

    - name: Push Docker image to Google Artifact Registry
      command: >
        docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
      environment:
        DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Configure kubectl
      command: gcloud container clusters get-credentials innotest-cluster --zone us-central1-c
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "true"

    - name: Apply Kubernetes manifests
      command: kubectl apply -f deployment.yaml -f service.yaml
