---
- name: Checkout Node.js Code
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure git is installed
      become: true
      apt:
        name: git
        state: present

    - name: Clone Node.js code from GitHub
      git:
        repo: https://github.com/mnagaraju5628/Testproject-INNO.git
        dest: /path/to/your/local/repo
        version: main  # replace 'main' with your branch name if different
      become: true
