name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    
     - name: Build Docker image for app
       run: |
          docker build -t my-test:latest -f /home/mnagaraju/actions-runner/Testproject-inno/horizon-dockerfile /home/mnagaraju/actions-runner/Testproject-inno

     - name: Build Docker image for node
       run: |
          docker build -t my-image:latest -f /home/mnagaraju/actions-runner/Testproject-inno/horizon-dockerfile-optimize /home/mnagaraju/actions-runner/Testproject-inno/
