name: Setup Workload Identity Federation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Get cluster credentials
        run: gcloud container clusters get-credentials testgke-cluster --region asia-south1-a
      
      - name: Create namespace
        run: |
            kubectl get namespace test-ns || kubectl create namespace test-ns
      
      - name: Create ServiceAccount
        run: |
            kubectl get serviceaccount test-ksa --namespace test-ns || kubectl create serviceaccount test-ksa --namespace test-ns
      
      - name: Bind IAM policy for GCS bucket creation
        run: |
          gcloud projects add-iam-policy-binding goldengate-1 \
            --role=roles/storage.admin \
            --member=serviceAccount:goldengate-1.svc.id.goog[test-ns/test-ksa] \
            --condition=None
      
      - name: Create GCS Bucket
        run: |
          gsutil mb gs://test-innobucket1534
      
      - name: Store application in GCS Bucket
        run: |
          gsutil cp /home/mnagaraju/actions-runner/Testproject-INNO gs://test-innobucket1534
