name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my_user_credentials  /home/mnagaraju/actions-runner/Testproject-inno/

      - name: Run Docker container
        run: |
          docker run -d --name my_user_credentials_container my_user_credentials 

      - name: Check decrypted credentials inside container
        run: |
          docker exec my_user_credentials_container cat /home/mnagaraju/actions-runner/Testproject-inno/credentials.txt
