name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install

    # Install the gcloud SDK with Workload Identity support
    - name: install the gcloud cli with Workload Identity
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        workload_identity: true
        export_default_credentials: true

  #  - name: build and push the docker image
  #    run: |
  #      gcloud auth configure-docker us-central1-docker.pkg.dev
  #      docker build -t us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest .
  #      docker push us-central1-docker.pkg.dev/goldengate-1/test-project/node:latest
    - name: deploy to gke
      run: |
        gcloud container clusters get-credentials innotest-cluster --region us-central1-c
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
