name: Node.js CI/CD with Workload Identity

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm install

    # Install the gcloud SDK with Workload Identity support
    - name: install the gcloud cli with Workload Identity
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        workload_identity: true
        export_default_credentials: true

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Set Google Cloud Project
      run: gcloud config set project ${{ secrets.GOOGLE_PROJECT }}

    - name: deploy to gke
      run: |
        gcloud container clusters get-credentials test-cluster --region asia-south1-a
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
