name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     # - name: Run decryption script
     #   run: |
     #     /home/mnagaraju/actions-runner/Testproject-inno/decrypt.sh

      - name: build image
        run: |
             docker build -t my-app:latest .  /home/mnagaraju/actions-runner/Testproject-inno/dockerfile-optimize
