name: Setup Workload Identity Federation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
      
      - name: Get cluster credentials
        run: gcloud container clusters get-credentials testgke-cluster --region asia-south1-a
      
      - name: Create namespace
        run: |
          kubectl create namespace test-ns
      
      - name: Create ServiceAccount
        run: |
          kubectl create serviceaccount KSA_NAME --namespace test-sa
      
      - name: Bind IAM policy
        run: |
          gcloud projects add-iam-policy-binding goldengate-1 \
            --role=roles/container.clusterViewer \
            --member=principal://iam.googleapis.com/projects/105619775743/locations/global/workloadIdentityPools/goldengate-1.svc.id.goog/subject/ns/test-ns/sa/test-sa \
            --condition=None

