name: 🔨 build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v3

      - name: 📦 Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 🔨 Install package dependencies
        run: npm ci

      - name: 🚀 Run project build command
        run: npm run build

      - name: Set gcloud account
        run: gcloud config set account testgcp-sa@goldengate-1.iam.gserviceaccount.com
        # Replace <ACCOUNT_EMAIL> with the email address associated with the service account.

      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push the Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/goldengate-1/demogcr-ar/node:latest .
          docker push us-central1-docker.pkg.dev/goldengate-1/demogcr-ar/node:latest

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials testgke-cluster --region asia-south1-a
          kubectl rollout restart deployment nodeapp-deployment 
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
