name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my_decrypt_credentials  /home/mnagaraju/actions-runner/Testproject-inno/

      - name: Recreate Docker Container
        run: |
          docker stop my_decrypt_credentials || true
          docker rm my_decrypt_credentials || true
          docker run --name my_decrypt_credentials -d my_decrypt_credentials
