name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4 # Update to a version that uses Node.js 20

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Update to a version that uses Node.js 20
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: npm install

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2 # Update to a version that uses Node.js 20
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set gcloud account
      run: gcloud config set account test-sa@goldengate-1.iam.gserviceaccount.com
      # Replace <ACCOUNT_EMAIL> with the email address associated with the service account.

    - name: Install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2 # Update to a version that uses Node.js 20
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        version: latest

    - name: Build and push the Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/goldengate-1/demogcr-ar/node:latest .
        docker push us-central1-docker.pkg.dev/goldengate-1/demogcr-ar/node:latest

    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials testgke-cluster --region asia-south1-a
        kubectl rollout restart deployment nodeapp-deployment 
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
