name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    - name: Decrypt credentials
      run: |
          # Path variables
          CREDENTIALS_ENC="/home/mnagaraju/actions-runner/Testproject-inno/credentials.enc"
          ENCRYPTION_KEY="/home/mnagaraju/actions-runner/Testproject-inno/encryption_key.txt"
          CREDENTIALS="/home/mnagaraju/actions-runner/Testproject-inno/credentials.txt"

          # Decrypt the credentials
          openssl enc -aes-256-cbc -pbkdf2 -d -in $CREDENTIALS_ENC -out $CREDENTIALS -pass file:$ENCRYPTION_KEY

          if [ $? -ne 0 ]; then
            echo "Decryption failed"
            exit 1
          fi

          echo "Decryption succeeded"

    - name: Deploy with Docker Compose
      run: |
          docker-compose -f /home/mnagaraju/actions-runner/Testproject-inno/docker-compose-test.yml up --build -d

