name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build_and_push_docker_image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Install Docker dependencies
        run: |
          sudo apt update
          sudo apt install -y containerd docker.io

      - name: Run Ansible playbook to build Docker image
        run: ansible-playbook ansible/repo.yaml
        env:
          PAT: ${{ secrets.PAT }}  # Required for Ansible to access the repository
