name: Migrate All Images to Artifact Registry

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  migrate:
    runs-on: self-hosted

    steps:
      # Step 1: Authenticate with GCR
      - name: Configure Docker CLI for GCR
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service-account-key: ${{ secrets.GCR_SA_KEY }}
          export-access-token: true
      
      # Step 2: Authenticate with Artifact Registry
      - name: Configure Docker CLI for Artifact Registry
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          docker-config: artifact
          project-id: ${{ secrets.ARTIFACT_PROJECT_ID }}
          service-account-key: ${{ secrets.ARTIFACT_SA_KEY }}
          export-access-token: true
      
      # Step 3: List images from GCR
      - name: List images from GCR
        id: list_images
        run: |
          gcloud container images list --format='value(name)' > images.txt
          cat images.txt
      
      # Step 4: Migrate each image to Artifact Registry
      - name: Migrate images to Artifact Registry
        run: |
          while IFS= read -r image; do
            echo "Processing image: $image"
            gcloud container images describe "gcr.io/${{ secrets.GCR_PROJECT_ID }}/$image" || exit 1
            docker pull "gcr.io/${{ secrets.GCR_PROJECT_ID }}/$image" || exit 1
            docker tag "gcr.io/${{ secrets.GCR_PROJECT_ID }}/$image" "us-central1-docker.pkg.dev/${{ secrets.ARTIFACT_PROJECT_ID }}/$image" || exit 1
            docker push "us-central1-docker.pkg.dev/${{ secrets.ARTIFACT_PROJECT_ID }}/$image" || exit 1
          done < images.txt
